### ISSUE TITLE
Cannot coerce class ‘"PCICt"’ to a data.frame

### ISSUE THREAD

**Issue by adrfantini** [pacificclimate/PCICt#1] opened 2019-03-03 10:36 UTC
It appears `PCICt` objects cannot be included in a `data.frame` column. This is a huge limitation, since it prevents usage with several base R workflows as well as modern packages such as `dplyr` or `tsibble`.
```R
library(PCICt)
> times = structure(c(778899600, 781491600, 784083600, 786675600, 789267600, 
791859600, 794451600, 797043600, 799635600, 802227600), cal = "360", months = c(30, 
30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30), dpy = 360, tzone = "GMT", units = "secs", class = "PCICt")
> data.frame(times)
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘"PCICt"’ to a data.frame
```
Is there any way to work around this limitation (other than transforming to POSIXct)?

**Comment by jameshiebert** [comment] 2023-02-15 00:22
Duplicate of #2 

This is now fixed:

```R
> devtools:::install_github("pacificclimate/PCICt")
Downloading GitHub repo pacificclimate/PCICt@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmps2zVPr/remotes19413743b730d/pacificclimate-PCICt-a895239/DESCRIPTION’ ... OK
─  preparing ‘PCICt’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘PCICt_0.5-4.4.tar.gz’
   
* installing *source* package ‘PCICt’ ...
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
gcc -I"/home/james/code/src/R-devel/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c PCICt_init.c -o PCICt_init.o
gcc -I"/home/james/code/src/R-devel/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c datetime_360.c -o datetime_360.o
gcc -shared -g -O2 -fpic -L/usr/local/lib -o PCICt.so PCICt_init.o datetime_360.o
installing to /home/james/code/src/R-devel/library/00LOCK-PCICt/00new/PCICt/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (PCICt)
> library(PCICt)
> times = structure(c(778899600, 781491600, 784083600, 786675600, 789267600, 
791859600, 794451600, 797043600, 799635600, 802227600), cal = "360", months = c(30, 
30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30), dpy = 360, tzone = "GMT", units = "secs", class = "PCICt")
> data.frame(times)
                 times
1  1995-01-16 01:00:00
2  1995-02-16 01:00:00
3  1995-03-16 01:00:00
4  1995-04-16 01:00:00
5  1995-05-16 01:00:00
6  1995-06-16 01:00:00
7  1995-07-16 01:00:00
8  1995-08-16 01:00:00
9  1995-09-16 01:00:00
10 1995-10-16 01:00:00
```

**Closed by jameshiebert** 2023-02-15 00:22 UTC
